---
    - name: Add Nginx Official repo - RedHat
      template:
        src: nginx.repo.j2
        dest: "/etc/yum.repos.d/nginx.repo"
      when: ansible_os_family == "RedHat"
       
    - name: Add Nginx Official repo - Debian
      template:
        src: nginx.list.j2
        dest: "/etc/apt/sources.list.d/nginx.list"
      when: ansible_os_family == "Debian"

    - name: Install Nginx on the server - RedHat
      yum: 
        name: nginx
        update_cache: yes
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Install Nginx on the server - Debian
      apt: 
        name: nginx
        update_cache: yes
        state: latest
        allow_unauthenticated: yes
      when: ansible_os_family == "Debian"

    - name: Enable the Nginx service
      systemd: 
          name: nginx
          state: started
          enabled: yes

      notify:
        - open_http_port
        - open_https_port
        - restart_nginx
    
   # Check if the Apache config file
   # - name: Check if the httpd config file exists
   #  stat: path=/etc/httpd/conf/httpd.conf
   #  register: conf_exists

   # If the conf file exists, backup the file
   #- name: Backup if the existing httpd.conf
   #  copy: remote_src=True
   #        src=/etc/httpd/conf/httpd.conf
   #        dest=/etc/httpd/conf/httpd.conf.orig
   #  when: conf_exists.stat.exists

   # Copy the conf file from the 'conf' directory to the remote server
   #- name: Copy our httpd.conf to the remote server
   #  copy: src=conf/httpd.conf
   #        dest=/etc/httpd/conf/httpd.conf
   #        owner=root
   #        group=root
   #        mode=0644
   #        backup=yes
