---
- hosts: webservers
  remote_user: root

  roles:
    - newuser

#- hosts: webservers
#  remote_user: ansibleuser
#  become: yes
#  become_method: sudo

#  roles:
#    - secure_ssh
#    - nginx
#    - nginx_vhosts
#    - gunicorn
#    - flask
