---
- hosts: webservers
  remote_user: root

  roles:
    - newuser

- hosts: webservers
  remote_user: ansibleuser
  become: yes
  become_method: sudo

  roles:
    - securessh
    - prerequisites
    - nginx
    - nginx_vhosts
    - python3

- hosts: webservers
  remote_user: flaskr
  become: yes
  become_method: sudo

  roles:
    - flask
#    - gunicorn
