---
    - name: Install git - Debian
      apt:
        name: git
        update_cache: yes
        state: latest
      when: ansible_os_family == "Debian"

    - name: Install git - RedHat
      yum:
        name: git
        update_cache: yes
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Copy venv script - RedHat
      template:
        src: venv_centos.sh.j2
        dest: ./venv.sh
      when:
        - ansible_os_family == "RedHat"

    - name: Copy venv script - Debian
      template:
        src: venv_debian.sh.j2
        dest: ./venv.sh
      when:
        - ansible_os_family == "Debian"

#    - name: Run venv installation - RedHat
#      script: py3_centos.sh
#      when: ansible_os_family == "RedHat"
