---
    - name: Create a new user
      user: 
        name: "{{ webuser_name }}"
        password: "{{ webuser_pass }}"
        shell: "/bin/bash"
        state: present
        system: no

    - file:
        path: "/home/{{ webuser_name }}/{{ item }}"
        owner: "{{ webuser_name }}"
        group: "{{ webuser_name }}"
        state: directory
        mode: 0755
      with_items:
        - "public_html"
        - "logs"
    - file:
        path: "/home/{{ webuser_name }}"
        owner: "{{ webuser_name }}"
        group: "{{ webuser_name }}"
        state: directory
        mode: 0711 
