---
    - name: Check if the Nginx configuration file exists
      stat:
        path: "/etc/nginx/nginx.conf"
      register:
        config_status

    - name: Backup the Nginx configuration file
      copy:
        remote_src: True
        src: "/etc/nginx/nginx.conf"
        dest: "/etc/nginx/nginx.conf.orig"
      when: config_status.stat.exists

    - name: Create the 'sites-available' and 'sites-enabled' dirs
      file:
        path: "/etc/nginx/{{ item }}"
        owner: "root"
        group: "root"
        state: directory
        mode: 0755
      with_items:
        - "sites-available"
        - "sites-enabled"
    
    - name: Include 'sites-enabled' in conf
      lineinfile:
        dest: "/etc/nginx/nginx.conf"
        line: "    include /etc/nginx/sites-enabled/*.conf;"
        insertafter: '^http'
        state: present

    - name: Add new vhosts conf file
      template:
        src: flaskr.com.conf.j2
        dest: "/etc/nginx/sites-available/flaskr.com.conf"

    - name: Symlink from 'sites-available' to 'sites-enabled'
      file:
        src: "/etc/nginx/sites-available/flaskr.com.conf"
        dest: "/etc/nginx/sites-enabled/flaskr.com.conf"
        owner: "root"
        group: "root"
        state: link

    - name: Check Nginx conf
      command: nginx -t
