---
    - name: Check if the Nginx configuration file exists
      stat:
        path: "/etc/nginx/nginx.conf"
      register:
        config_status

    - name: Backup the Nginx configuration file
      copy:
        remote_src: True
        src: "/etc/nginx/nginx.conf"
        dest: "/etc/nginx/nginx.conf.orig"
      when: config_status.stat.exists

    - name: Create the 'sites-available' and 'sites-enabled' dirs
      file:
        path: "/etc/nginx/{{ item }}"
        owner: "root"
        group: "root"
        state: directory
        mode: 0755
      with_items:
        - "sites-available"
        - "sites-enabled"
    
    -  
